server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/youapp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.springframework.security: TRACE
    org.hibernate.orm.connections.pooling: WARN
    org.hibernate.orm.jdbc.extract: TRACE
    i.lettuce.core.protocol.CommandEncoder: TRACE

