dependencies{
    implementation(libs.caffeine.cache)
    implementation(libs.kotlin.reflect)
    implementation(rootProject.libs.bundles.web.flux)
    implementation("com.sv.youapp.common:authorization-commons")
    implementation("org.springframework.security:spring-security-web")
    implementation("org.springframework.security:spring-security-config")
    implementation("jakarta.validation:jakarta.validation-api")
    testImplementation("io.projectreactor:reactor-test")
    implementation(rootProject.libs.spring.boot.starter.logbook)
}
