server:
  port: 8082
#spring:
  #autoconfigure:
    #exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
logging:
  level:
    org.springframework.security: TRACE
    org.hibernate.orm.connections.pooling: WARN
